sonar.projectKey=MyDiary
sonar.qualitygate.wait=true

sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=vendor/**,var/**,migrations/**,data/**,logs/**,.scannerwork/**
