filebeat.inputs:
  - type: log
    paths:
      - /logs/nginx/*.log
    fields:
      log_service: nginx
    fields_under_root: true

  - type: log
    paths:
      - /logs/postgres/*.log
    fields:
      log_service: postgres
    fields_under_root: true

  - type: log
    paths:
      - /logs/redis/*.log
    fields:
      log_service: redis
    fields_under_root: true

  - type: log
    paths:
      - /logs/php/*.log
      - /logs/messenger-worker/*.log
    fields:
      log_service: php
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: "${ELASTICSEARCH_USERNAME:-}"
  password: "${ELASTICSEARCH_PASSWORD:-}"

setup.kibana:
  host: "${KIBANA_HOST:-}"
