<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804114140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9F85E0677 ON app_user (username)');
        $this->addSql('CREATE TABLE audio_recording (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, telegram_message_id VARCHAR(255) NOT NULL, telegram_file_unique_id VARCHAR(255) NOT NULL, file_path VARCHAR(1024) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, duration_seconds INT NOT NULL, error_code VARCHAR(64) DEFAULT NULL, error_message VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EF02265316AA253 ON audio_recording (telegram_message_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EF0226536270CA63 ON audio_recording (telegram_file_unique_id)');
        $this->addSql('CREATE TABLE daily_summary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, summary_text TEXT NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11C9B797AA9E377A ON daily_summary (date)');
        $this->addSql('CREATE TABLE daily_summary_topic (daily_summary_id INT NOT NULL, topic_id INT NOT NULL, PRIMARY KEY (daily_summary_id, topic_id))');
        $this->addSql('CREATE INDEX IDX_A35DA8B3D721293F ON daily_summary_topic (daily_summary_id)');
        $this->addSql('CREATE INDEX IDX_A35DA8B31F55203D ON daily_summary_topic (topic_id)');
        $this->addSql('CREATE TABLE topic (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9D40DE1B5E237E06 ON topic (name)');
        $this->addSql('CREATE TABLE transcription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, file_path VARCHAR(1024) NOT NULL, edited_manually BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, audio_recording_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_329CE984256BB73E ON transcription (audio_recording_id)');
        $this->addSql('ALTER TABLE daily_summary_topic ADD CONSTRAINT FK_A35DA8B3D721293F FOREIGN KEY (daily_summary_id) REFERENCES daily_summary (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_summary_topic ADD CONSTRAINT FK_A35DA8B31F55203D FOREIGN KEY (topic_id) REFERENCES topic (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transcription ADD CONSTRAINT FK_329CE984256BB73E FOREIGN KEY (audio_recording_id) REFERENCES audio_recording (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_summary_topic DROP CONSTRAINT FK_A35DA8B3D721293F');
        $this->addSql('ALTER TABLE daily_summary_topic DROP CONSTRAINT FK_A35DA8B31F55203D');
        $this->addSql('ALTER TABLE transcription DROP CONSTRAINT FK_329CE984256BB73E');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE audio_recording');
        $this->addSql('DROP TABLE daily_summary');
        $this->addSql('DROP TABLE daily_summary_topic');
        $this->addSql('DROP TABLE topic');
        $this->addSql('DROP TABLE transcription');
    }
}
